name: stars_race
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  rxdart: ^0.22.1
  flare_flutter: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^2.1.0
  build_runner: ^1.3.1

flutter:

  uses-material-design: true

  fonts:
    - family:  MaxwellRegular
      fonts:
        - asset: assets/fonts/MaxwellRegular.ttf
        - asset: assets/fonts/MaxwellBold.ttf
          weight: 700

  assets:
    - assets/flare/starsRace.flr
